export const actionTypes = {
  GET_TOURNAMENTS: 'GET_TOURNAMENTS',
  CREATE_TOURNAMENT: 'CREATE_TOURNAMENT',
  UPDATE_TOURNAMENT: 'UPDATE_TOURNAMENT',
  DELETE_TOURNAMENT: 'DELETE_TOURNAMENT',
  SET_LOADING: 'SET_LOADING',
  SET_HAS_ERROR: 'SET_HAS_ERROR',
  SEARCH_TOURNAMENT: 'SEARCH_TOURNAMENT'
};
